### ISSUE TITLE
alt-f4 works

### ISSUE THREAD

**Issue by AlignedCookie88** [ThatBlueEnder/Kiosk#1]
alt-f4 works, please fix

**Comment by ThatBlueEnder** [comment]
Sorry to hear that. Does this look the same on your side?
![prismlauncher_0U5o3ln15x](https://github.com/ThatBlueEnder/Kiosk/assets/148366561/f8020449-045a-4f60-886e-183b26a6d953)

**Comment by AlignedCookie88** [comment]
ah, i'm an idiot and didnt look at the modrinth page before installing, sorry to disturb you

**Comment by ThatBlueEnder** [comment]
It's chill
